library("lintr")
#lint("R/entropy_util.R")
#lint("R/zzz.R")
#lint("R/entropy_unittest.R")
#lint("R/utils.R")
#lint("R/spikes.R")
#lint("R/spikelist_functions.R")
#lint("R/si.R")
#lint("R/permPlot.R")
lint("R/networkspikes_functions.R")

lint("R/networkspikes.R")
library("styler")
style_pkg()