# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

count_ns <- function(spikes, beg, end, wid, nbins) {
    .Call('_meaRtools_count_ns', PACKAGE = 'meaRtools', spikes, beg, end, wid, nbins)
}

frate_counts <- function(spikes, beg, end, wid, nbins) {
    .Call('_meaRtools_frate_counts', PACKAGE = 'meaRtools', spikes, beg, end, wid, nbins)
}

run_TMcpp <- function(dt, start, end, spike_times_1, spike_times_2) {
    .Call('_meaRtools_run_TMcpp', PACKAGE = 'meaRtools', dt, start, end, spike_times_1, spike_times_2)
}

tiling_correlogramcpp <- function(spikes, n, nspikes, first_spike, start, end, dt, tau_sep, tau_max) {
    .Call('_meaRtools_tiling_correlogramcpp', PACKAGE = 'meaRtools', spikes, n, nspikes, first_spike, start, end, dt, tau_sep, tau_max)
}

tiling_correlogramcpp_index <- function(spikes, n, nspikes, first_spike, start, end, dt, tau_sep, tau_max, a, b) {
    .Call('_meaRtools_tiling_correlogramcpp_index', PACKAGE = 'meaRtools', spikes, n, nspikes, first_spike, start, end, dt, tau_sep, tau_max, a, b)
}

sttc_allspikes1 <- function(spikes, dt, beg, end) {
    .Call('_meaRtools_sttc_allspikes1', PACKAGE = 'meaRtools', spikes, dt, beg, end)
}

sttcp_ab <- function(a, b, start, end, dt, tau_sep, tau_max) {
    .Call('_meaRtools_sttcp_ab', PACKAGE = 'meaRtools', a, b, start, end, dt, tau_sep, tau_max)
}

