// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// count_ns
NumericVector count_ns(List spikes, double beg, double end, double wid, double nbins);
RcppExport SEXP _meaRtools_count_ns(SEXP spikesSEXP, SEXP begSEXP, SEXP endSEXP, SEXP widSEXP, SEXP nbinsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type spikes(spikesSEXP);
    Rcpp::traits::input_parameter< double >::type beg(begSEXP);
    Rcpp::traits::input_parameter< double >::type end(endSEXP);
    Rcpp::traits::input_parameter< double >::type wid(widSEXP);
    Rcpp::traits::input_parameter< double >::type nbins(nbinsSEXP);
    rcpp_result_gen = Rcpp::wrap(count_ns(spikes, beg, end, wid, nbins));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world2
List rcpp_hello_world2();
RcppExport SEXP _meaRtools_rcpp_hello_world2() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world2());
    return rcpp_result_gen;
END_RCPP
}
// frate_counts
NumericMatrix frate_counts(List spikes, double beg, double end, double wid, int nbins);
RcppExport SEXP _meaRtools_frate_counts(SEXP spikesSEXP, SEXP begSEXP, SEXP endSEXP, SEXP widSEXP, SEXP nbinsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type spikes(spikesSEXP);
    Rcpp::traits::input_parameter< double >::type beg(begSEXP);
    Rcpp::traits::input_parameter< double >::type end(endSEXP);
    Rcpp::traits::input_parameter< double >::type wid(widSEXP);
    Rcpp::traits::input_parameter< int >::type nbins(nbinsSEXP);
    rcpp_result_gen = Rcpp::wrap(frate_counts(spikes, beg, end, wid, nbins));
    return rcpp_result_gen;
END_RCPP
}
// run_TMcpp
double run_TMcpp(double dt, double start, double end, NumericVector spike_times_1, NumericVector spike_times_2);
RcppExport SEXP _meaRtools_run_TMcpp(SEXP dtSEXP, SEXP startSEXP, SEXP endSEXP, SEXP spike_times_1SEXP, SEXP spike_times_2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< double >::type start(startSEXP);
    Rcpp::traits::input_parameter< double >::type end(endSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type spike_times_1(spike_times_1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type spike_times_2(spike_times_2SEXP);
    rcpp_result_gen = Rcpp::wrap(run_TMcpp(dt, start, end, spike_times_1, spike_times_2));
    return rcpp_result_gen;
END_RCPP
}
// tiling_correlogramcpp
NumericVector tiling_correlogramcpp(NumericVector spikes, int n, IntegerVector nspikes, IntegerVector first_spike, double start, double end, /* recording time */                                     double dt, double tau_sep, double tau_max);
RcppExport SEXP _meaRtools_tiling_correlogramcpp(SEXP spikesSEXP, SEXP nSEXP, SEXP nspikesSEXP, SEXP first_spikeSEXP, SEXP startSEXP, SEXP endSEXP, SEXP dtSEXP, SEXP tau_sepSEXP, SEXP tau_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type spikes(spikesSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nspikes(nspikesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type first_spike(first_spikeSEXP);
    Rcpp::traits::input_parameter< double >::type start(startSEXP);
    Rcpp::traits::input_parameter< double >::type end(endSEXP);
    Rcpp::traits::input_parameter< /* recording time */                                     double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< double >::type tau_sep(tau_sepSEXP);
    Rcpp::traits::input_parameter< double >::type tau_max(tau_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(tiling_correlogramcpp(spikes, n, nspikes, first_spike, start, end, dt, tau_sep, tau_max));
    return rcpp_result_gen;
END_RCPP
}
// tiling_correlogramcpp_index
NumericVector tiling_correlogramcpp_index(NumericVector spikes, int n, IntegerVector nspikes, IntegerVector first_spike, double start, double end, double dt, double tau_sep, double tau_max, int a, int b);
RcppExport SEXP _meaRtools_tiling_correlogramcpp_index(SEXP spikesSEXP, SEXP nSEXP, SEXP nspikesSEXP, SEXP first_spikeSEXP, SEXP startSEXP, SEXP endSEXP, SEXP dtSEXP, SEXP tau_sepSEXP, SEXP tau_maxSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type spikes(spikesSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nspikes(nspikesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type first_spike(first_spikeSEXP);
    Rcpp::traits::input_parameter< double >::type start(startSEXP);
    Rcpp::traits::input_parameter< double >::type end(endSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< double >::type tau_sep(tau_sepSEXP);
    Rcpp::traits::input_parameter< double >::type tau_max(tau_maxSEXP);
    Rcpp::traits::input_parameter< int >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(tiling_correlogramcpp_index(spikes, n, nspikes, first_spike, start, end, dt, tau_sep, tau_max, a, b));
    return rcpp_result_gen;
END_RCPP
}
// sttc_allspikes1
NumericMatrix sttc_allspikes1(List spikes, double dt, double beg, double end);
RcppExport SEXP _meaRtools_sttc_allspikes1(SEXP spikesSEXP, SEXP dtSEXP, SEXP begSEXP, SEXP endSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type spikes(spikesSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< double >::type beg(begSEXP);
    Rcpp::traits::input_parameter< double >::type end(endSEXP);
    rcpp_result_gen = Rcpp::wrap(sttc_allspikes1(spikes, dt, beg, end));
    return rcpp_result_gen;
END_RCPP
}
// sttcp_ab
NumericVector sttcp_ab(NumericVector a, NumericVector b, double start, double end, double dt, double tau_sep, double tau_max);
RcppExport SEXP _meaRtools_sttcp_ab(SEXP aSEXP, SEXP bSEXP, SEXP startSEXP, SEXP endSEXP, SEXP dtSEXP, SEXP tau_sepSEXP, SEXP tau_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type start(startSEXP);
    Rcpp::traits::input_parameter< double >::type end(endSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< double >::type tau_sep(tau_sepSEXP);
    Rcpp::traits::input_parameter< double >::type tau_max(tau_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(sttcp_ab(a, b, start, end, dt, tau_sep, tau_max));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_meaRtools_count_ns", (DL_FUNC) &_meaRtools_count_ns, 5},
    {"_meaRtools_rcpp_hello_world2", (DL_FUNC) &_meaRtools_rcpp_hello_world2, 0},
    {"_meaRtools_frate_counts", (DL_FUNC) &_meaRtools_frate_counts, 5},
    {"_meaRtools_run_TMcpp", (DL_FUNC) &_meaRtools_run_TMcpp, 5},
    {"_meaRtools_tiling_correlogramcpp", (DL_FUNC) &_meaRtools_tiling_correlogramcpp, 9},
    {"_meaRtools_tiling_correlogramcpp_index", (DL_FUNC) &_meaRtools_tiling_correlogramcpp_index, 11},
    {"_meaRtools_sttc_allspikes1", (DL_FUNC) &_meaRtools_sttc_allspikes1, 4},
    {"_meaRtools_sttcp_ab", (DL_FUNC) &_meaRtools_sttcp_ab, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_meaRtools(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
